
[general]
	#The alternative names of this material.
	alternativeNames = []
	#The byproducts of this material.
	extras = []
	#The module blacklist of this material.
	moduleBlacklist = []
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#The model type of the material.
	modelType = "metallic"
	#The color of this material.
	color = 12878923

[create]
	#The default byproduct material to output in Create's crushing.
	byproduct = "minecraft:cobblestone"

[futurepack]
	#The byproduct material to output in Futurepack's Centrifuge.
	byproduct = "minecraft:cobblestone"

[mekanism]
	#The default base to use in Mekanism's Combiner to recreate ores.
	ore_base = "#forge:cobblestone/normal"
	#The default base to use in Mekanism's Combiner to recreate ores.
	oreBase = "#forge:cobblestone/normal"

[exnihilosequentia]
	#Should gravel sieve recipes be added.
	sieveGravel = true
	#Should crushed netherrack sieve recipes be added.
	sieveCrushedNetherrack = false
	#Should crushed end stone sieve recipes be added.
	sieveCrushedEndstone = false
	#The output chance of the sieve recipes added using a flint mesh.
	sieveFlintChance = 0.0
	#The output chance of the sieve recipes added using an iron mesh.
	sieveIronChance = 0.0
	#The output chance of the sieve recipes added using a diamond mesh.
	sieveDiamondChance = 0.0

