
[general]
	#The alternative names of this material.
	alternativeNames = []
	#The byproducts of this material.
	extras = []
	#The module blacklist of this material.
	moduleBlacklist = []
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#The model type of the material.
	modelType = "dust"
	#The color of this material.
	color = 11774634

[create]
	#The default byproduct material to output in Create's crushing.
	byproduct = "minecraft:cobblestone"

[futurepack]
	#The byproduct material to output in Futurepack's Centrifuge.
	byproduct = "minecraft:cobblestone"

[mekanism]
	#The default base to use in Mekanism's Combiner to recreate ores.
	ore_base = "#forge:cobblestone/normal"
	#The default base to use in Mekanism's Combiner to recreate ores.
	oreBase = "#forge:cobblestone/normal"

[exnihilosequentia]
	#Should dust sieve recipes be added.
	sieveGravel = true
	#Should soul sand sieve recipes be added.
	sieveCrushedNetherrack = false
	#The output chance of the sieve recipes added using an iron mesh.
	sieveIronChance = 0.0625
	#The output chance of the sieve recipes added using a diamond mesh.
	sieveDiamondChance = 0.125

